Add register app
petconnection/backend pull request #33
Opened 2018-09-27 17:44 UTC by pabloriutort

To test:
1. Register a token with django shell
```
from models import Token
t = Token()
t.save()
```
2. Get token code and go to the register URL with code as parameter `localhost:<port>/register/<code>/`
3. Try the form
4. Try accessing same URL with invalid token code

2018-11-15 21:55 UTC, Nosk14 requested changes
The same token can be used to register a new entity as many times as the user wants. We should add a new field to know if it is already used or maybe we can just set the expiry time to epoch or something like that to invalidate it.

2018-11-15 21:55 UTC, Nosk14 commented on register/views.py
> +            return redirect('/')
I think it would be nice to redirect the user to the backoffice login page

2018-11-15 21:55 UTC, Nosk14 commented on register/models.py
> +            self.expiry = timezone.now() + timezone.timedelta(days=1)
I don't feel comfortable with these two lines. I mean, when you create a new token like `t = Token()` you are creating an empty object and the valuers are set when you save it. I think the values should be set on the constructor. 
We can talk about it

2018-12-13 15:57 UTC, pabloriutort commented
Migrating PR to new branch feature/register

2018-12-13 15:57 UTC, closed without merging